### ISSUE TITLE
500 error when importing egg to Pterodactyl panel v0.7

### ISSUE THREAD

**Issue by alexbgameson** [GeyserMC/pterodactyl-stuff#22]
I get a 500 error when importing egg to Pterodactyl panel v0.7 and egg is not added.

**Comment by Grizzly90** [comment]
I would recommend using Pterodactyl 1.4 as v0.7 has reached the end of life and isn't supported any more...

The eggs have changed on the new version

**Comment by rtm516** [comment]
0.7 is EOL and therefore out of support so any issues with this egg and it will not be resolved unless the same occurs with the latest Pterodactyl.
