### ISSUE TITLE
geyser-spigot port not set

### ISSUE THREAD

**Issue by alexbgameson** [GeyserMC/pterodactyl-stuff#32]
The geyser-spigot port defaults to 19132 and not the port assigned to the server by pterodactyl. Only Minecraft server port is set.

bedrock:
  # The IP address that will listen for connections.
  # There is no reason to change this unless you want to limit what IPs can connect to your server.
  address: 0.0.0.0
  # The port that will listen for connections
  port: 19132

**Comment by Grizzly90** [comment]
you need to set the port in the server config. This can't be done automatic.

**Comment by alexbgameson** [comment]
Thank you! I have set it to auto set that port on the egg config page.
