### ISSUE TITLE
GeyserMC Egg not supported on ARM

### ISSUE THREAD

**Issue by mind-overflow** [GeyserMC/pterodactyl-stuff#46]
Hello there,
I tried setting up a GeyserMC standalone server on Pterodactyl. The host is a Oracle VM running on Ubuntu Server for ARM. The egg pulls and installs without issues, however, upon trying to start it, I get
```
[Pterodactyl Daemon]: Finished pulling Docker container image
exec /bin/bash: exec format error
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
```
This usually means that the pulled image is not packaging binaries (I assume Java binaries) compiled for the ARM architecture. It would be great to have ARM images available too.  
  
Thank you!

**Comment by rtm516** [comment]
arm docker containers should now be built and usable with the new eggs, please update to the latest egg config
